#!/bin/python3

from parsing import connect_to_server, parse_args, communication_server_client, logger

def send_recv_command(socket_connection, info_client):
    """_summary_

    Args:
        socket_connection (_type_): _description_
        info_client (_type_): _description_
    """
    tab_command = []
    # while (True):
    #     msg = socket_connection.recv(2048).decode('utf-8')
    #     if (msg == "dead"):
    #         print("The connection between the server and the AI ​​has been lost because the AI ​​has therefore died in the game.")
    #         sys.exit(0)
    #     print(msg)
    #     break
    return

def main():
    """The main function for launch all other functions (main logic)
    """
    port, team_name, machine_name = parse_args()
    socket_connection = connect_to_server(port, machine_name)
    info_client = communication_server_client(socket_connection, team_name)
    send_recv_command(socket_connection, info_client)
    logger.info("The program has just ended")

if __name__ == '__main__':
    main()