#!/bin/python3

from parsing import connect_to_server, parse_args, communication_server_client, logger
from handle_commands import send_recv_command
from constant import Direction
from agent import Agent

#😁​🎯​🫵​🥸​💋​✋​​6️⃣7️⃣​🤚​👅​🙈​🙊​🧌​🐸​
def main():
    """The main function for launch all other functions (main logic)
    """
    port, team_name, machine_name = parse_args()
    socket_connection = connect_to_server(port, machine_name)
    info_client = communication_server_client(socket_connection, team_name)
    agent = Agent()
    agent.unused_slots = info_client["client_num"]
    send_recv_command(socket_connection, info_client, agent)
    logger.info("The program has just ended")

if __name__ == '__main__':
    main()